//! Markdown rendering of a [`CacheStudy`].
//!
//! The report is the deliverable a human reads; it is regenerated by re-running
//! the study as the cache grows (Issue #1920).

use super::stats::{CacheStudy, GroupStats, Predictor, VANISHING_GAIN};

/// Renders the study as a Markdown report.
#[must_use]
pub fn render_markdown(study: &CacheStudy) -> String {
    let mut out = String::new();
    out.push_str("# Discovery Candidates Cache Study\n\n");
    out.push_str(&overview(study));
    out.push_str(&group_table(
        "## Volume by strategy",
        "Strategy",
        &study.by_strategy,
    ));
    out.push_str(&group_table(
        "## Volume by model hash",
        "Model hash",
        &study.by_model_hash,
    ));
    out.push_str(&group_table("## Volume by day", "Day", &study.by_day));
    out.push_str(&group_table(
        "## Volume by discovery version",
        "Version",
        &study.by_version,
    ));
    out.push_str(&group_table(
        "## Volume by request kind",
        "`rustRequest` kind",
        &study.by_request_kind,
    ));
    out.push_str(&predictor_table(&study.predictors));
    out
}

fn overview(study: &CacheStudy) -> String {
    let overall = &study.overall;
    let success_rate = overall
        .success_rate()
        .map_or_else(|| "n/a".to_string(), |r| format!("{:.1}%", r * 100.0));
    format!(
        "## Overview\n\n\
         | Measure | Value |\n| --- | --- |\n\
         | Records | {total} |\n\
         | From working tree | {live} |\n\
         | Recovered from git history | {recovered} |\n\
         | Successes | {successes} |\n\
         | Failures | {failures} |\n\
         | Success rate | {success_rate} |\n\
         | Mean success `scoreDelta` | {mean} |\n\
         | Median success `scoreDelta` | {median} |\n\
         | Largest success `scoreDelta` | {max} |\n\
         | Successes at or below {vanishing} | {vanishing_count} |\n\n",
        total = study.total,
        live = study.live,
        recovered = study.recovered,
        successes = overall.successes,
        failures = overall.failures,
        mean = sci(overall.mean_success_delta),
        median = sci(overall.median_success_delta),
        max = sci(overall.max_success_delta),
        vanishing = sci(VANISHING_GAIN),
        vanishing_count = study.vanishing_successes,
    )
}

fn group_table(heading: &str, key_column: &str, groups: &[GroupStats]) -> String {
    let mut out = format!("{heading}\n\n");
    if groups.is_empty() {
        out.push_str("_No records._\n\n");
        return out;
    }
    out.push_str(&format!(
        "| {key_column} | Records | Success | Failure | Success rate | Mean gain | Median gain | Max gain | Total gain |\n\
         | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n"
    ));
    for group in groups {
        let rate = group
            .success_rate()
            .map_or_else(|| "n/a".to_string(), |r| format!("{:.1}%", r * 100.0));
        out.push_str(&format!(
            "| {label} | {total} | {successes} | {failures} | {rate} | {mean} | {median} | {max} | {sum} |\n",
            label = group.label,
            total = group.total(),
            successes = group.successes,
            failures = group.failures,
            mean = sci(group.mean_success_delta),
            median = sci(group.median_success_delta),
            max = sci(group.max_success_delta),
            sum = sci(group.total_success_delta),
        ));
    }
    out.push('\n');
    out
}

fn predictor_table(predictors: &[Predictor]) -> String {
    let mut out = String::from(
        "## Gain-size predictors\n\n\
         `r` is the Pearson correlation of the field (log-scaled where it spans \
         orders of magnitude) against `log10(scoreDelta)` over successes, and \
         against the success indicator over all records.\n\n",
    );
    if predictors.is_empty() {
        out.push_str("_No numeric predictors present in this corpus._\n");
        return out;
    }
    out.push_str(
        "| Field | Gain n | r vs log gain | Outcome n | r vs success |\n| --- | ---: | ---: | ---: | ---: |\n",
    );
    for predictor in predictors {
        out.push_str(&format!(
            "| `{label}` | {gain_n} | {r_gain} | {outcome_n} | {r_success} |\n",
            label = predictor.label,
            gain_n = predictor.gain_samples,
            r_gain = correlation(predictor.r_vs_log_gain),
            outcome_n = predictor.outcome_samples,
            r_success = correlation(predictor.r_vs_success),
        ));
    }
    out
}

fn correlation(r: Option<f64>) -> String {
    r.map_or_else(|| "n/a".to_string(), |r| format!("{r:+.3}"))
}

fn sci(value: f64) -> String {
    if value.is_nan() {
        return "n/a".to_string();
    }
    if value == 0.0 {
        return "0".to_string();
    }
    format!("{value:.3e}")
}
