//! Issue #1878: the CI `version-increment` job must not re-resolve `Cargo.lock`.
//!
//! The job bumps the patch version in `Cargo.toml`, then commits and pushes the
//! result with the `ACTIONS_PUSH` PAT. It used to run a bare `cargo update`,
//! which re-resolves every direct **and transitive** dependency to the newest
//! published version with no age check — bypassing both the Renovate
//! `minimumReleaseAge` window and the `VIBE_BUMP_QUARANTINE_HOURS` gate in
//! `bump-deps.sh`. A crate published minutes earlier landed in the committed
//! lockfile on every PR. Same class of bypass as Issue #1865, on the CI path.
//!
//! These tests extract the real `run:` script from `.github/workflows/ci.yml`
//! and execute it against a throwaway git repository with a stubbed `cargo` on
//! `PATH`, asserting the observable behaviour:
//!
//!   1. The crate's own version is still recorded in `Cargo.lock`, and every
//!      `cargo update` the step issues is scoped to the workspace — never a
//!      full re-resolve.
//!   2. If the lockfile moves beyond the crate's own version, the step fails
//!      loud instead of committing an unquarantined dependency graph.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::{Command, Stdio};

const STEP_NAME: &str = "Check for source changes and increment version";

/// The lockfile fixture: this crate plus one external dependency whose
/// resolution must survive the step untouched.
const LOCKFILE: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "neat_ai_discovery"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
"#;

const MANIFEST: &str =
    "[package]\nname = \"neat_ai_discovery\"\nversion = \"0.1.0\"\nedition = \"2024\"\n";

/// Extract the shell body of the named `run: |` step from a workflow file.
fn step_script(workflow: &str, step_name: &str) -> String {
    let body = fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join(".github/workflows")
            .join(workflow),
    )
    .expect("read workflow");
    let header = format!("    - name: {step_name}\n");
    let start = body
        .find(&header)
        .unwrap_or_else(|| panic!("step `{step_name}` not found in {workflow}"));
    let after = &body[start + header.len()..];
    let run_at = after
        .find("      run: |\n")
        .unwrap_or_else(|| panic!("step `{step_name}` has no `run: |` block"));
    let mut script = String::new();
    for line in after[run_at + "      run: |\n".len()..].lines() {
        if line.trim().is_empty() {
            script.push('\n');
            continue;
        }
        let Some(stripped) = line.strip_prefix("        ") else {
            break;
        };
        script.push_str(stripped);
        script.push('\n');
    }
    script
}

/// Write an executable stub script into `dir`.
fn write_stub(dir: &Path, name: &str, body: &str) {
    let path = dir.join(name);
    fs::write(&path, body).expect("write stub");
    let mut perms = fs::metadata(&path).expect("stat stub").permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&path, perms).expect("chmod stub");
}

fn git(repo: &Path, args: &[&str]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(repo)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .expect("run git");
    assert!(status.success(), "git {args:?} failed");
}

struct Run {
    success: bool,
    stdout: String,
    stderr: String,
    manifest: String,
    lockfile: String,
    cargo_calls: String,
}

/// Run the extracted step in a throwaway repo. `extra_lock_mutation` is a `sed`
/// expression the stubbed `cargo update` also applies to `Cargo.lock`, used to
/// simulate a dependency re-resolve.
fn run_step(extra_lock_mutation: Option<&str>) -> Run {
    let tmp = tempfile::tempdir().expect("temp dir");
    let repo = tmp.path().join("repo");
    let bin = tmp.path().join("bin");
    fs::create_dir_all(&repo).expect("create repo dir");
    fs::create_dir_all(&bin).expect("create stub bin dir");

    fs::write(repo.join("Cargo.toml"), MANIFEST).expect("write Cargo.toml");
    fs::write(repo.join("Cargo.lock"), LOCKFILE).expect("write Cargo.lock");
    git(&repo, &["init", "-q"]);
    git(&repo, &["add", "Cargo.toml", "Cargo.lock"]);
    git(
        &repo,
        &[
            "-c",
            "user.email=test@example.com",
            "-c",
            "user.name=test",
            "commit",
            "-q",
            "-m",
            "fixture",
        ],
    );

    // Stub `cargo`: record every sub-command, and on `update` record the
    // crate's own new version in the lockfile the way real cargo does.
    let log = tmp.path().join("cargo-invocations.log");
    let extra = extra_lock_mutation
        .map(|expr| format!("  sed -i.bak '{expr}' Cargo.lock\n"))
        .unwrap_or_default();
    write_stub(
        &bin,
        "cargo",
        &format!(
            "#!/bin/bash\nprintf '%s\\n' \"$*\" >> '{log}'\n\
             if [ \"$1\" = update ]; then\n\
             \x20 sed -i.bak 's/^version = \"0.1.0\"$/version = \"0.1.1\"/' Cargo.lock\n\
             {extra}\
             \x20 rm -f Cargo.lock.bak\n\
             fi\nexit 0\n",
            log = log.display(),
        ),
    );

    let output = Command::new("bash")
        .arg("-c")
        .arg(step_script("ci.yml", STEP_NAME))
        .current_dir(&repo)
        .env("PATH", format!("{}:/usr/bin:/bin", bin.display()))
        .env("HOME", tmp.path())
        .stdin(Stdio::null())
        .output()
        .expect("run version-increment step");

    Run {
        success: output.status.success(),
        stdout: String::from_utf8_lossy(&output.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        manifest: fs::read_to_string(repo.join("Cargo.toml")).expect("read Cargo.toml"),
        lockfile: fs::read_to_string(repo.join("Cargo.lock")).expect("read Cargo.lock"),
        cargo_calls: fs::read_to_string(&log).unwrap_or_default(),
    }
}

#[test]
fn version_increment_step_never_re_resolves_the_lockfile() {
    let run = run_step(None);
    assert!(
        run.success,
        "version-increment step failed (Issue #1878)\nstdout:\n{}\nstderr:\n{}",
        run.stdout, run.stderr
    );

    // The step's actual job: bump the patch version and record it in the lock.
    assert!(
        run.manifest.contains("version = \"0.1.1\""),
        "step must increment the patch version in Cargo.toml — got:\n{}",
        run.manifest
    );
    assert!(
        run.lockfile.contains("version = \"0.1.1\""),
        "step must record the new crate version in Cargo.lock — got:\n{}",
        run.lockfile
    );
    // The external dependency must be left exactly where it was.
    assert!(
        run.lockfile.contains("version = \"1.0.0\""),
        "step must not move dependency resolutions in Cargo.lock (Issue #1878) — got:\n{}",
        run.lockfile
    );

    let updates: Vec<&str> = run
        .cargo_calls
        .lines()
        .filter(|line| line.starts_with("update"))
        .collect();
    assert!(
        !updates.is_empty(),
        "step must still refresh the crate's own lockfile entry — recorded cargo calls:\n{}",
        run.cargo_calls
    );
    for call in updates {
        assert!(
            call.contains("--workspace")
                || call.contains(" -w")
                || call.contains("--precise")
                || call.contains("-p "),
            "`cargo {call}` re-resolves every direct and transitive dependency with no \
             quarantine window (Issue #1878) — the update must be scoped to this crate"
        );
    }
}

#[test]
fn version_increment_step_fails_loud_when_dependencies_move() {
    // Simulate a re-resolve: the dependency's pinned version moves too.
    let run = run_step(Some("s/^version = \"1.0.0\"$/version = \"1.0.1\"/"));
    assert!(
        !run.success,
        "step must fail loud when Cargo.lock changes beyond this crate's own \
         version — dependency movement belongs to ./bump-deps.sh and Renovate, \
         which enforce the quarantine window (Issue #1878)\nstdout:\n{}\nstderr:\n{}",
        run.stdout, run.stderr
    );
    let combined = format!("{}{}", run.stdout, run.stderr);
    assert!(
        combined.contains("Cargo.lock"),
        "the failure must name Cargo.lock so the cause is obvious (Issue #1878) — got:\n{combined}"
    );
}
