//! Output squash mismatch detection module (Issue #546).
//!
//! Detects when output neurons use an activation function that doesn't match
//! the target data range, trapping the network in a local minimum. For example,
//! if targets are generated by TANH (smooth, range [-1,1]), but the output neuron
//! uses `HARD_TANH` (piecewise linear, flat gradients at extremes), the network
//! cannot converge properly regardless of weight/bias tuning.
//!
//! ## Detection Strategies
//!
//! 1. **Clipping analysis**: Checks if a significant fraction of activations are
//!    at the saturation bounds of the current squash function, suggesting the
//!    function is too aggressive in its non-linearity.
//!
//! 2. **Range mismatch**: Detects when the activation range doesn't match the
//!    target data range (e.g., LOGISTIC \[0,1\] with targets in \[-1,1\]).
//!
//! 3. **Unbounded mismatch**: Detects when an unbounded activation has high errors
//!    outside the expected target range.
//!
//! 4. **Pre-activation squash comparison**: When pre-activation values are available,
//!    simulates what alternative squash functions would produce and selects the one
//!    that best reduces error against the observed activation/error patterns.

#![allow(clippy::cast_precision_loss)] // Intentional numeric casts for GPU/neural network computation (Issue #873)
use crate::activations::apply_scalar_squash;
use crate::analysis::constants::MIN_DISCOVERY_SAMPLE_COUNT as MIN_SAMPLES;
use crate::analysis::cost_function_hint::CostFunctionHint;
use crate::types::DiscoverRecord;
use crate::{CoordinatedStructuralCandidateJson, CoordinatedStructuralOpJson};

/// Fraction of activations at saturation bounds to trigger clipping detection.
const CLIPPING_FRACTION_THRESHOLD: f32 = 0.15;

/// Minimum mean error to consider the neuron as having a meaningful problem.
const MIN_MEAN_ERROR_THRESHOLD: f32 = 0.05;

/// Ratio of error-at-bounds vs error-at-centre to flag a mismatch.
const BOUND_ERROR_RATIO_THRESHOLD: f32 = 1.5;

/// Tolerance for detecting activations at saturation bounds.
const BOUND_TOLERANCE: f32 = 0.02;

/// Minimum error ratio for unbounded-to-bounded recommendation.
const UNBOUNDED_HIGH_ERROR_FRACTION: f32 = 0.25;

/// Minimum relative error reduction to consider a squash replacement worthwhile
/// via pre-activation comparison (Strategy 4).
const MIN_ERROR_REDUCTION_FRACTION: f32 = 0.15;

/// Candidate squash functions evaluated during pre-activation comparison.
const CANDIDATE_SQUASHES: &[&str] = &[
    "TANH",
    "LOGISTIC",
    "IDENTITY",
    "SOFTSIGN",
    "HARD_TANH",
    "RELU",
    "SELU",
    "MISH",
    "SWISH",
];

/// A detected output squash mismatch candidate.
#[derive(Debug, Clone)]
pub struct OutputSquashMismatchCandidate {
    /// UUID of the output neuron.
    pub neuron_uuid: String,
    /// Current activation function.
    pub current_squash: String,
    /// Recommended replacement activation function.
    pub recommended_squash: String,
    /// Confidence in the recommendation (0.0 to 1.0).
    pub confidence: f32,
    /// Estimated improvement from switching.
    pub estimated_improvement: f32,
    /// Mean error across all observations.
    pub mean_error: f32,
    /// Human-readable explanation.
    pub reason: String,
}

/// Returns the theoretical output bounds `(min, max)` for bounded activations.
fn activation_bounds(squash: &str) -> Option<(f32, f32)> {
    match squash {
        "HARD_TANH" | "CLIPPED" => Some((-1.0, 1.0)),
        "TANH" | "BIPOLAR_SIGMOID" => Some((-1.0, 1.0)),
        "LOGISTIC" => Some((0.0, 1.0)),
        "BIPOLAR" | "STEP" => Some((-1.0, 1.0)),
        "RELU" => Some((0.0, f32::INFINITY)),
        "RELU6" => Some((0.0, 6.0)),
        "SOFTSIGN" | "ARCTAN" => Some((-1.0, 1.0)),
        _ => None,
    }
}

/// Returns whether a squash function has hard clipping (piecewise linear bounds).
fn is_hard_clipping(squash: &str) -> bool {
    matches!(
        squash,
        "HARD_TANH" | "CLIPPED" | "RELU" | "RELU6" | "BIPOLAR" | "STEP"
    )
}

/// Returns whether a squash function is unbounded (output can exceed any finite range).
fn is_unbounded(squash: &str) -> bool {
    matches!(
        squash,
        "IDENTITY" | "ELU" | "SELU" | "LEAKYRELU" | "SOFTPLUS" | "BENT_IDENTITY" | "BENTIDENTITY"
    )
}

/// Compute the fraction of activations near the saturation bounds.
fn compute_clipping_fraction(records: &[DiscoverRecord], lower: f32, upper: f32) -> f32 {
    if records.is_empty() {
        return 0.0;
    }
    let at_bounds = records
        .iter()
        .filter(|r| {
            (r.activation - lower).abs() < BOUND_TOLERANCE
                || (r.activation - upper).abs() < BOUND_TOLERANCE
        })
        .count();
    at_bounds as f32 / records.len() as f32
}

/// Compute the mean error for records at bounds vs away from bounds.
fn compute_bound_error_ratio(records: &[DiscoverRecord], lower: f32, upper: f32) -> (f32, f32) {
    let (mut bound_error_sum, mut bound_count) = (0.0f32, 0usize);
    let (mut centre_error_sum, mut centre_count) = (0.0f32, 0usize);

    for r in records {
        let error = r.errors.first().copied().unwrap_or(0.0).abs();
        let at_bound = (r.activation - lower).abs() < BOUND_TOLERANCE
            || (r.activation - upper).abs() < BOUND_TOLERANCE;
        if at_bound {
            bound_error_sum += error;
            bound_count += 1;
        } else {
            centre_error_sum += error;
            centre_count += 1;
        }
    }

    let bound_mean = if bound_count > 0 {
        bound_error_sum / bound_count as f32
    } else {
        0.0
    };
    let centre_mean = if centre_count > 0 {
        centre_error_sum / centre_count as f32
    } else {
        0.0
    };
    (bound_mean, centre_mean)
}

/// Select the best replacement squash function for a bounded activation.
fn recommend_replacement(current_squash: &str, records: &[DiscoverRecord]) -> (String, f32) {
    // Check if activations suggest symmetric [-1, 1] range
    let has_negative = records.iter().any(|r| r.activation < -0.01);
    let has_positive = records.iter().any(|r| r.activation > 0.01);
    let symmetric = has_negative && has_positive;

    match current_squash {
        "HARD_TANH" | "CLIPPED" => {
            // HARD_TANH clips hard at ±1 — smooth TANH is the natural replacement
            ("TANH".to_string(), 0.8)
        }
        "LOGISTIC" => {
            if symmetric {
                // Targets include negative values but LOGISTIC only outputs [0, 1]
                ("TANH".to_string(), 0.7)
            } else {
                ("TANH".to_string(), 0.5)
            }
        }
        "BIPOLAR" | "STEP" => {
            // Discrete output — smooth replacement
            ("TANH".to_string(), 0.6)
        }
        "RELU" | "RELU6" => {
            if symmetric {
                ("TANH".to_string(), 0.7)
            } else {
                ("SOFTPLUS".to_string(), 0.5)
            }
        }
        _ => {
            // Default to TANH for any bounded → smooth transition
            ("TANH".to_string(), 0.5)
        }
    }
}

/// Evaluate alternative squash functions against pre-activation values.
///
/// For each candidate squash, applies the function to all pre-activation values and
/// computes what the mean absolute error would be. Returns the best alternative
/// (if any) that would reduce error by at least `MIN_ERROR_REDUCTION_FRACTION`.
fn evaluate_alternative_squashes(
    current_squash: &str,
    records: &[DiscoverRecord],
    current_mean_error: f32,
) -> Option<(String, f32, f32)> {
    // Collect records with pre-activation values
    let records_with_values: Vec<&DiscoverRecord> =
        records.iter().filter(|r| r.value.is_some()).collect();

    if records_with_values.len() < MIN_SAMPLES {
        return None;
    }

    // For each observation, the "target" output is approximated as:
    //   target ≈ activation + error
    // (since error = activation - target in the network's perspective,
    //  target ≈ activation - error; but errors can be signed so we use
    //  the actual error sign from the record)
    let targets: Vec<f32> = records_with_values
        .iter()
        .map(|r| r.activation - r.errors.first().copied().unwrap_or(0.0))
        .collect();

    let pre_activations: Vec<f32> = records_with_values.iter().filter_map(|r| r.value).collect();

    let mut best: Option<(String, f32, f32)> = None;

    for &candidate_name in CANDIDATE_SQUASHES {
        // Skip the current squash function
        if candidate_name.eq_ignore_ascii_case(current_squash) {
            continue;
        }

        // Compute mean absolute error if we used this candidate squash
        let mut total_error = 0.0f32;
        let mut valid_count = 0usize;

        for (pre_act, target) in pre_activations.iter().zip(targets.iter()) {
            if let Some(simulated) = apply_scalar_squash(candidate_name, *pre_act)
                && simulated.is_finite()
            {
                total_error += (simulated - target).abs();
                valid_count += 1;
            }
        }

        if valid_count < MIN_SAMPLES {
            continue;
        }

        let candidate_mean_error = total_error / valid_count as f32;

        // Check if this candidate meaningfully reduces error
        let error_reduction = current_mean_error - candidate_mean_error;
        let reduction_fraction = if current_mean_error > 1e-6 {
            error_reduction / current_mean_error
        } else {
            0.0
        };

        if reduction_fraction > MIN_ERROR_REDUCTION_FRACTION
            && best.as_ref().is_none_or(|b| candidate_mean_error < b.1)
        {
            best = Some((
                candidate_name.to_string(),
                candidate_mean_error,
                reduction_fraction,
            ));
        }
    }

    best
}

/// Detect output squash mismatches.
///
/// # Arguments
/// * `output_neurons` - Slice of `(uuid, squash, bias)` tuples for output neurons.
/// * `neuron_records` - Slice of `(uuid, records)` pairs with observation data.
///
/// # Returns
/// Vector of detected mismatch candidates, sorted by estimated improvement (best first).
///
/// This entry point preserves the pre-Issue-#1250 behaviour and assumes the
/// recorded error is a linear residual. Callers that know the network's
/// cost function should prefer [`detect_output_squash_mismatches_with_cost_hint`].
pub fn detect_output_squash_mismatches(
    output_neurons: &[(String, String, f32)],
    neuron_records: &[(String, impl AsRef<[DiscoverRecord]>)],
) -> Vec<OutputSquashMismatchCandidate> {
    detect_output_squash_mismatches_with_cost_hint(
        output_neurons,
        neuron_records,
        CostFunctionHint::Unknown,
    )
}

/// Cost-aware variant of [`detect_output_squash_mismatches`] (Issue #1250).
///
/// Strategy 4 (pre-activation squash comparison) reconstructs an "implied
/// target" as `activation − error`. That identity only holds for
/// linear-residual costs (`MSE`/`MAE`/`CE`). When `cost_hint` reports a
/// non-linear residual (`MAPE`, `MSLE`, `HINGE`, `CATEGORICAL_ERROR`),
/// Strategy 4 is skipped; the remaining strategies (clipping, range
/// mismatch, unbounded mismatch) use only `|error|` aggregates and remain
/// valid.
pub fn detect_output_squash_mismatches_with_cost_hint(
    output_neurons: &[(String, String, f32)],
    neuron_records: &[(String, impl AsRef<[DiscoverRecord]>)],
    cost_hint: CostFunctionHint,
) -> Vec<OutputSquashMismatchCandidate> {
    let mut candidates = Vec::with_capacity(output_neurons.len());

    for (uuid, squash, _bias) in output_neurons {
        let Some((_id, records)) = neuron_records.iter().find(|(u, _)| u == uuid) else {
            continue;
        };
        let records = records.as_ref();

        if records.len() < MIN_SAMPLES {
            continue;
        }

        // Compute mean error
        let mean_error: f32 = records
            .iter()
            .map(|r| r.errors.first().copied().unwrap_or(0.0).abs())
            .sum::<f32>()
            / records.len() as f32;

        if mean_error < MIN_MEAN_ERROR_THRESHOLD {
            continue;
        }

        // Strategy 1: Bounded activation with clipping at bounds
        if let Some((lower, upper_bound)) = activation_bounds(squash)
            && upper_bound.is_finite()
        {
            let clipping_fraction = compute_clipping_fraction(records, lower, upper_bound);

            let (bound_error, centre_error) =
                compute_bound_error_ratio(records, lower, upper_bound);

            let error_ratio = if centre_error > 1e-6 {
                bound_error / centre_error
            } else if bound_error > 1e-6 {
                BOUND_ERROR_RATIO_THRESHOLD + 1.0
            } else {
                0.0
            };

            // Detect: significant clipping AND higher error at bounds
            let has_clipping = clipping_fraction > CLIPPING_FRACTION_THRESHOLD;
            let has_bound_error = error_ratio > BOUND_ERROR_RATIO_THRESHOLD;
            let is_hard_clip = is_hard_clipping(squash);

            if has_clipping && (has_bound_error || is_hard_clip) {
                let (recommended, base_confidence) = recommend_replacement(squash, records);

                // Don't recommend same squash
                if recommended.eq_ignore_ascii_case(squash) {
                    continue;
                }

                let sample_confidence = (records.len() as f32 / 100.0).min(1.0);
                let confidence = (base_confidence * 0.6
                    + sample_confidence * 0.2
                    + clipping_fraction.min(1.0) * 0.2)
                    .clamp(0.0, 1.0);

                // Estimated improvement: fraction of error attributable to squash mismatch
                let estimated_improvement = mean_error * clipping_fraction * 0.5;

                candidates.push(OutputSquashMismatchCandidate {
                    neuron_uuid: uuid.clone(),
                    current_squash: squash.clone(),
                    recommended_squash: recommended.clone(),
                    confidence,
                    estimated_improvement,
                    mean_error,
                    reason: format!(
                        "Output neuron {uuid} uses {squash} but {:.0}% of activations are clipped at bounds with {error_ratio:.1}x higher error at bounds vs centre. {recommended} would provide smoother gradients. (Issue #546)",
                        clipping_fraction * 100.0,
                    ),
                });

                continue;
            }
        }

        // Strategy 2: Bounded activation whose range doesn't match target data
        // e.g., LOGISTIC outputs [0, 1] but targets are in [-1, 1]
        if let Some((lower, upper_bound)) = activation_bounds(squash)
            && upper_bound.is_finite()
        {
            // Check if the activation range is non-negative but errors are high
            // (suggests target range extends below the activation's minimum)
            let min_activation = records
                .iter()
                .map(|r| r.activation)
                .fold(f32::INFINITY, f32::min);

            // If activation minimum > -0.05 but we have high mean error, the
            // activation range may not cover negative targets
            let all_positive_activations = min_activation > -0.05;
            let high_error_fraction = records
                .iter()
                .filter(|r| r.errors.first().copied().unwrap_or(0.0).abs() > mean_error)
                .count() as f32
                / records.len() as f32;

            // LOGISTIC-specific: outputs only [0,1] but targets may be [-1,1]
            if all_positive_activations && lower >= -0.05 && high_error_fraction > 0.3 {
                let recommended = "TANH".to_string();

                if !recommended.eq_ignore_ascii_case(squash) {
                    let sample_confidence = (records.len() as f32 / 100.0).min(1.0);
                    let confidence =
                        (0.6 * 0.6 + sample_confidence * 0.2 + high_error_fraction.min(1.0) * 0.2)
                            .clamp(0.0, 1.0);
                    let estimated_improvement = mean_error * high_error_fraction * 0.3;

                    candidates.push(OutputSquashMismatchCandidate {
                        neuron_uuid: uuid.clone(),
                        current_squash: squash.clone(),
                        recommended_squash: recommended.clone(),
                        confidence,
                        estimated_improvement,
                        mean_error,
                        reason: format!(
                            "Output neuron {uuid} uses {squash} (range [{lower:.1}, {upper_bound:.1}]) but {:.0}% of samples have above-average error, suggesting target range extends beyond activation range. {recommended} would provide symmetric [-1,1] range. (Issue #546)",
                            high_error_fraction * 100.0,
                        ),
                    });

                    continue;
                }
            }
        }

        // Strategy 3: Unbounded activation with targets that need bounding
        if is_unbounded(squash) {
            // Check if errors are high when activation is far from [-1, 1]
            let out_of_range_count = records.iter().filter(|r| r.activation.abs() > 1.05).count();
            let out_of_range_fraction = out_of_range_count as f32 / records.len() as f32;

            let out_of_range_error: f32 = records
                .iter()
                .filter(|r| r.activation.abs() > 1.05)
                .map(|r| r.errors.first().copied().unwrap_or(0.0).abs())
                .sum::<f32>();
            let out_of_range_mean_error = if out_of_range_count > 0 {
                out_of_range_error / out_of_range_count as f32
            } else {
                0.0
            };

            if out_of_range_fraction > UNBOUNDED_HIGH_ERROR_FRACTION
                && out_of_range_mean_error > mean_error * 1.2
            {
                let has_negative = records.iter().any(|r| r.activation < -0.01);
                let recommended = if has_negative {
                    "TANH".to_string()
                } else {
                    "LOGISTIC".to_string()
                };

                let confidence = (out_of_range_fraction * 0.5
                    + (records.len() as f32 / 100.0).min(1.0) * 0.5)
                    .clamp(0.0, 1.0);
                let estimated_improvement = out_of_range_mean_error * out_of_range_fraction * 0.3;

                let error_ratio_display = if mean_error > 1e-6 {
                    out_of_range_mean_error / mean_error
                } else {
                    1.0
                };

                candidates.push(OutputSquashMismatchCandidate {
                    neuron_uuid: uuid.clone(),
                    current_squash: squash.clone(),
                    recommended_squash: recommended.clone(),
                    confidence,
                    estimated_improvement,
                    mean_error,
                    reason: format!(
                        "Output neuron {uuid} uses unbounded {squash} but {:.0}% of activations exceed [-1,1] with {error_ratio_display:.1}x higher error outside bounds. {recommended} would bound the output. (Issue #546)",
                        out_of_range_fraction * 100.0,
                    ),
                });

                continue;
            }
        }

        // Strategy 4: Pre-activation squash comparison
        // When pre-activation values are available, simulate alternative squash
        // functions and pick the one that best reduces error.
        //
        // Issue #1250: this strategy reconstructs an implied target as
        // `activation − error`, which only holds for linear-residual costs.
        // Skip it when the caller has positively declared a non-linear cost
        // (MAPE / MSLE / HINGE / CATEGORICAL_ERROR).
        if !cost_hint.allows_linear_target_reconstruction() {
            continue;
        }
        if let Some((best_squash, _best_error, reduction_fraction)) =
            evaluate_alternative_squashes(squash, records, mean_error)
        {
            let sample_confidence = (records.len() as f32 / 100.0).min(1.0);
            let confidence =
                (reduction_fraction.min(1.0) * 0.6 + sample_confidence * 0.4).clamp(0.0, 1.0);
            let estimated_improvement = mean_error * reduction_fraction * 0.5;

            candidates.push(OutputSquashMismatchCandidate {
                neuron_uuid: uuid.clone(),
                current_squash: squash.clone(),
                recommended_squash: best_squash.clone(),
                confidence,
                estimated_improvement,
                mean_error,
                reason: format!(
                    "Output neuron {uuid} uses {squash} but simulating pre-activation values through {best_squash} would reduce error by {:.0}%. (Issue #546)",
                    reduction_fraction * 100.0,
                ),
            });
        }
    }

    // Sort by estimated improvement descending
    candidates.sort_by(|a, b| {
        b.estimated_improvement
            .partial_cmp(&a.estimated_improvement)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    candidates
}

/// Convert output squash mismatch candidates to coordinated structural candidates.
pub fn output_squash_mismatch_to_coordinated_candidates(
    candidates: &[OutputSquashMismatchCandidate],
) -> Vec<CoordinatedStructuralCandidateJson> {
    candidates
        .iter()
        .map(|c| CoordinatedStructuralCandidateJson {
            operations: vec![CoordinatedStructuralOpJson::ChangeSquash {
                neuron_uuid: c.neuron_uuid.clone(),
                squash: c.recommended_squash.clone(),
            }],
            expected_creature_score_gain: c.estimated_improvement,
            comment: Some(c.reason.clone()),
        })
        .collect()
}
