//! Candidate recommendation integration tests.

#[path = "../common/mod.rs"]
mod common;

mod issue_1059_disable_batch_successful;
mod issue_1247_categorical_error_hardening;
mod issue_1249_categorical_error_sse_gating;
mod issue_1313_role_aware_output_squash;
mod issue_1316_output_bias_drift_one_hot_capacity_starvation;
mod issue_1319_one_hot_per_class_capacity_allocation;
mod issue_1321_output_competition_lateral_inhibition;
mod issue_1713_aggregate_gate;
mod issue_189_synergistic_discovery;
mod issue_202_epistatic_neuron_pairs;
mod issue_230_multi_hop_candidate_analysis;
mod issue_402_range_aware_weight_optimisation;
mod issue_421_gradient_based_discovery;
mod issue_422_topology_aware_discovery;
mod issue_423_sample_weighted_discovery;
mod issue_431_activation_recommendation;
mod issue_507_micro_nudge_variant;
mod issue_509_deduplicate_dominant_neuron;
mod issue_548_squash_weight_rescale;
mod issue_549_topology_diversification;
mod issue_550_weight_magnitude_reset;
mod issue_551_bias_perturbation_regime_shift;
mod issue_570_skip_connection_discovery;
mod issue_788_high_error_squash_exploration;
mod issue_908_fan_in_candidates;
mod issue_965_batch_successful_grouping;
