//! Post-processing for synapse analysis results
//!
//! This module handles impact-based discounting, sorting, diversification,
//! truncation, and metadata assembly for synapse analysis candidates.
//! Extracted from mod.rs as part of Issue #482.

use crate::CandidateSynapseJson;
use crate::analysis::diagnostics::compute_impact_scores_for_discounting;
use crate::analysis::utils::{shuffle_within_top_k, verbose_enabled};
use std::collections::HashMap;

use super::filtering::truncate_combined_synapse_candidate_sets;
use super::scoring::{
    apply_logistic_prediction_calibration, apply_prediction_calibration, apply_source_type_boost,
    apply_synapse_pessimism_discount, apply_target_type_boost,
};
use crate::analysis::cache::RecordCache;
use crate::analysis::samples::EPSILON;
use crate::analysis::scoring::calibration_correction::{
    CHANGE_TYPE_ADD_SYNAPSES, CHANGE_TYPE_COORDINATED_STRUCTURAL, CHANGE_TYPE_REMOVE_NEURON,
    CalibrationCorrection,
};

/// Drop add-synapse candidates whose `expected_creature_score_gain` is below
/// the absolute noise floor (Issue #1191).
///
/// Reads the configured floor via
/// [`min_expected_gain_floor_for_synapses`](crate::analysis::constants::min_expected_gain_floor_for_synapses)
/// (overridable through `NEAT_AI_DISCOVERY_MIN_EXPECTED_GAIN`). The gains
/// reaching this filter are post-calibration, so the configured screen is
/// converted into that scale by `SYNAPSE_PREDICTION_CALIBRATION` first — before
/// Issue #1778 it was compared raw, which made the floor 3333× stricter than
/// intended and unreachable by any candidate the pipeline can produce. Each
/// drop is
/// recorded against the global
/// [`candidates_below_gain_floor_total`](crate::observability::GainFloorMetrics)
/// counter so operators can see how many candidates the floor removes per
/// batch. Returns the number of candidates dropped.
///
/// Coordinated-structural candidates have their own (smaller) post-discount
/// noise floor applied later in the pipeline and so are intentionally not
/// gated here.
pub fn apply_min_expected_gain_floor_for_synapses(
    candidates: &mut Vec<CandidateSynapseJson>,
) -> usize {
    let floor = crate::analysis::constants::min_expected_gain_floor_for_synapses();
    let before = candidates.len();
    candidates.retain(|c| c.expected_creature_score_gain >= floor);
    let dropped = before - candidates.len();
    crate::observability::global_gain_floor_metrics().record_dropped(dropped);
    dropped
}

/// Log the distribution of synapse candidates by source type (Issue #910).
///
/// Tracks how many add-synapse candidates are generated by source type:
/// input-to-hidden, input-to-output, hidden-to-hidden, and hidden-to-output.
/// This diagnostic helps verify that hidden-to-hidden candidates are being
/// generated and not crowded out by input-sourced candidates.
fn log_source_type_distribution(
    candidates: &[CandidateSynapseJson],
    neuron_type_map: &HashMap<&str, &str>,
) {
    use crate::analysis::utils::parse_input_index;

    let mut input_to_hidden = 0u32;
    let mut input_to_output = 0u32;
    let mut hidden_to_hidden = 0u32;
    let mut hidden_to_output = 0u32;

    for c in candidates {
        let source_is_input = parse_input_index(&c.from_neuron_uuid).is_some();
        let target_is_output = neuron_type_map
            .get(c.to_neuron_uuid.as_str())
            .is_some_and(|t| *t == "output");

        match (source_is_input, target_is_output) {
            (true, false) => input_to_hidden += 1,
            (true, true) => input_to_output += 1,
            (false, false) => hidden_to_hidden += 1,
            (false, true) => hidden_to_output += 1,
        }
    }

    tracing::info!(
        total = candidates.len(),
        input_to_hidden,
        input_to_output,
        hidden_to_hidden,
        hidden_to_output,
        "Synapse candidate source type distribution (Issue #910)"
    );
}

/// Scale a raw neuron-level prediction by the target neuron's fraction of total creature error.
///
/// Issue #730: Raw improvement predictions measure error reduction at a single target neuron,
/// but these do not translate directly to creature-level score changes. A synapse improving
/// one neuron's error by 5% does not mean 5% creature improvement — it depends on what
/// fraction of total creature error that neuron contributes.
///
/// ## Formula
///
/// ```text
/// error_fraction = target_error_sq / total_error_sq
/// scaled_prediction = raw_prediction × error_fraction
/// ```
///
/// ## Arguments
///
/// * `raw_prediction` — Neuron-level improvement (fraction of target error reduced)
/// * `target_error_sq` — Sum of squared errors for the target neuron
/// * `total_error_sq` — Sum of squared errors across all focus neurons
pub fn scale_by_error_fraction(
    raw_prediction: f32,
    target_error_sq: f32,
    total_error_sq: f32,
) -> f32 {
    if total_error_sq <= EPSILON {
        return 0.0;
    }
    let fraction = (target_error_sq / total_error_sq).clamp(0.0, 1.0);
    raw_prediction * fraction
}

/// Compute sum of squared errors for each neuron in the creature from the cache.
///
/// Issue #730: Used to determine what fraction of total creature error each target
/// neuron contributes, enabling creature-level prediction calibration.
///
/// ## Quantised `{0, 1}` error regime (Issue #1249)
///
/// Under `CATEGORICAL_ERROR` the per-neuron `Σ e² = Σ e` equals the
/// neuron's misclassification count. The downstream consumer
/// ([`scale_by_error_fraction`]) uses the **ratio**
/// `target_error_sq / total_error_sq`, which under the regime collapses
/// to "fraction of network misclassifications attributable to this
/// neuron" — still a sensible cost-agnostic impact-scaling factor. The
/// SSE sum is therefore retained on purpose; gating it off would zero
/// every neuron's impact and silence the discovery pipeline.
fn compute_neuron_error_sq_map<'a>(
    input: &'a crate::AnalyzeSynapsesInput,
    cache: &RecordCache,
) -> HashMap<&'a str, f32> {
    let mut error_sq_map = HashMap::new();
    for neuron in &input.creature.neurons {
        if let Ok(records) = cache.get(&neuron.uuid) {
            let error_sq: f32 = records
                .iter()
                .flat_map(|r| r.errors.iter())
                .filter(|e| e.is_finite())
                .map(|e| e * e)
                .sum();
            if error_sq > EPSILON {
                error_sq_map.insert(neuron.uuid.as_str(), error_sq);
            }
        }
    }
    error_sq_map
}

/// Apply impact-based discounting to a single helpful synapse candidate.
///
/// Updates `target_neuron_impact`, `expected_creature_error_reduction`,
/// and `expected_creature_score_gain` based on the target neuron's distance
/// from outputs. Also applies creature-level error fraction scaling (Issue #730)
/// and source-type and target-type boosts (Issues #467, #468).
#[allow(clippy::too_many_arguments)]
fn apply_impact_to_helpful(
    candidate: &mut CandidateSynapseJson,
    impact_scores: &HashMap<String, f32>,
    neuron_type_map: &HashMap<&str, &str>,
    target_squash_map: &HashMap<&str, &str>,
    order_map: &HashMap<String, usize>,
    target_error_sq: f32,
    total_error_sq: f32,
    calibration_correction: &CalibrationCorrection,
) {
    // Populate indices for debugging/analysis (consistent with CandidateNeuronJson).
    candidate.from_neuron_index = order_map.get(&candidate.from_neuron_uuid).copied();
    candidate.to_neuron_index = order_map.get(&candidate.to_neuron_uuid).copied();

    let is_hidden = neuron_type_map
        .get(candidate.to_neuron_uuid.as_str())
        .is_none_or(|t| *t != "output"); // Default to hidden if type unknown

    let impact = if is_hidden {
        if let Some(&impact) = impact_scores.get(&candidate.to_neuron_uuid) {
            impact.clamp(0.0, 1.0)
        } else {
            // No impact score means disconnected from outputs - heavy discount
            0.1
        }
    } else {
        // Output neuron - full impact
        1.0
    };

    // Update creature-level metrics
    candidate.target_neuron_impact = impact;
    let original = candidate.expected_creature_error_reduction;

    // Issue #730: Scale by target neuron's fraction of total creature error.
    // This converts neuron-level improvement to creature-level improvement.
    candidate.expected_creature_error_reduction = scale_by_error_fraction(
        candidate.expected_creature_error_reduction,
        target_error_sq,
        total_error_sq,
    );

    candidate.expected_creature_error_reduction *= impact;
    candidate.expected_creature_score_gain = candidate.expected_creature_error_reduction;

    // Issue #789: Apply synapse-specific pessimism discount based on improved sample ratio.
    // Raw improvement percentages are neuron-level estimates that do not generalise
    // directly to creature-level score gains (18,500× over-estimation in production).
    // Synapse candidates use the most aggressive discounting because the multi-weight
    // search (9 variants) creates selection bias that overfits to sample data,
    // contributing to the 0% success rate observed in production discovery-cache data.
    candidate.expected_creature_score_gain = apply_synapse_pessimism_discount(
        candidate.expected_creature_score_gain,
        candidate.improved_count,
        candidate.total_count,
        // Issue #1161: combine the binary improved-ratio with the magnitude-weighted ratio.
        candidate.improvement_magnitude_ratio,
    );

    // Issue #467: Apply source-type prioritisation boost for input-neuron sources.
    candidate.expected_creature_score_gain = apply_source_type_boost(
        candidate.expected_creature_score_gain,
        &candidate.from_neuron_uuid,
    );

    // Issue #468: Apply target-type prioritisation boost for existing hidden targets.
    candidate.expected_creature_score_gain = apply_target_type_boost(
        candidate.expected_creature_score_gain,
        &candidate.to_neuron_uuid,
        neuron_type_map,
    );

    // Issue #1056: Apply logistic prediction calibration to correct massive overestimation.
    // The non-linear (logistic) calibration uses the improved ratio to modulate the
    // base calibration factor, providing better correction than a flat multiplier.
    // Production discovery-cache data shows add-synapses has ~0.1% actual success rate (3/1001).
    //
    // Issue #1131: Multiplied by the per-creature calibration correction derived
    // from the failure cache, so creatures drifting from the global baseline
    // receive additional per-creature discounting.
    //
    // Issue #1162: prefer the per-(change_type, target_squash) specific
    // correction when enough failure-cache evidence is available; otherwise
    // fall back to the per-change_type correction.
    let target_squash = target_squash_map
        .get(candidate.to_neuron_uuid.as_str())
        .copied();
    let synapse_calibration = crate::analysis::constants::SYNAPSE_PREDICTION_CALIBRATION
        * calibration_correction.correction_for(CHANGE_TYPE_ADD_SYNAPSES, target_squash);
    candidate.expected_creature_score_gain = apply_logistic_prediction_calibration(
        candidate.expected_creature_score_gain,
        candidate.improved_count,
        candidate.total_count,
        synapse_calibration,
    );

    if verbose_enabled() && is_hidden {
        tracing::debug!(
            to_neuron_uuid = &candidate.to_neuron_uuid[..12.min(candidate.to_neuron_uuid.len())],
            impact = format_args!("{impact:.3}"),
            original_pct = format_args!("{:.4}", original * 100.0),
            discounted_pct = format_args!("{:.4}", candidate.expected_creature_score_gain * 100.0),
            "Synapse candidate impact discounting applied"
        );
    }
}

/// Apply impact-based discounting to a single harmful synapse candidate.
fn apply_impact_to_harmful(
    candidate: &mut CandidateSynapseJson,
    impact_scores: &HashMap<String, f32>,
    neuron_type_map: &HashMap<&str, &str>,
    target_squash_map: &HashMap<&str, &str>,
    order_map: &HashMap<String, usize>,
    calibration_correction: &CalibrationCorrection,
) {
    candidate.from_neuron_index = order_map.get(&candidate.from_neuron_uuid).copied();
    candidate.to_neuron_index = order_map.get(&candidate.to_neuron_uuid).copied();

    let is_hidden = neuron_type_map
        .get(candidate.to_neuron_uuid.as_str())
        .is_none_or(|t| *t != "output");

    let impact = if is_hidden {
        if let Some(&impact) = impact_scores.get(&candidate.to_neuron_uuid) {
            impact.clamp(0.0, 1.0)
        } else {
            0.1
        }
    } else {
        1.0
    };

    candidate.target_neuron_impact = impact;
    candidate.expected_creature_error_reduction *= impact;
    candidate.expected_creature_score_gain = candidate.expected_creature_error_reduction;

    // Issue #789: Apply synapse-specific pessimism discount based on improved sample ratio.
    candidate.expected_creature_score_gain = apply_synapse_pessimism_discount(
        candidate.expected_creature_score_gain,
        candidate.improved_count,
        candidate.total_count,
        // Issue #1161: combine the binary improved-ratio with the magnitude-weighted ratio.
        candidate.improvement_magnitude_ratio,
    );

    // Issue #1056: Apply logistic prediction calibration to harmful candidates.
    // Issue #1131: Scaled by the per-creature failure-cache correction.
    // Issue #1162: prefer the per-(change_type, target_squash) specific value.
    let target_squash = target_squash_map
        .get(candidate.to_neuron_uuid.as_str())
        .copied();
    let synapse_calibration = crate::analysis::constants::SYNAPSE_PREDICTION_CALIBRATION
        * calibration_correction.correction_for(CHANGE_TYPE_ADD_SYNAPSES, target_squash);
    candidate.expected_creature_score_gain = apply_logistic_prediction_calibration(
        candidate.expected_creature_score_gain,
        candidate.improved_count,
        candidate.total_count,
        synapse_calibration,
    );
}

/// Apply impact-based discounting and prediction calibration to a coordinated structural
/// candidate.
///
/// Uses the last operation's target neuron UUID to determine impact, since multi-op
/// groups ultimately adjust the inputs of a target neuron.
///
/// Issue #1058: Removed the separate `COORDINATED_PESSIMISM_DISCOUNT` flat discount.
/// The pessimism discount has been folded into the per-op-count empirical factors
/// applied in `candidate_aggregation::apply_operation_count_discount`. This avoids
/// the three-layer compound discount that was too aggressive and poorly calibrated.
/// Determine the failure-cache change-type key for a coordinated candidate
/// (Issue #1425).
///
/// A coordinated candidate consisting of a single `RemoveNeuron` operation is
/// functionally a `remove-neuron` (harmful-neuron) change and is recorded under
/// [`CHANGE_TYPE_REMOVE_NEURON`] in the failure cache. Every other coordinated
/// candidate (multi-op groups, or single ops of other kinds) keeps the generic
/// [`CHANGE_TYPE_COORDINATED_STRUCTURAL`] key, preserving existing behaviour.
fn coordinated_candidate_change_type(
    candidate: &crate::CoordinatedStructuralCandidateJson,
) -> &'static str {
    if candidate.operations.len() == 1
        && matches!(
            candidate.operations.first(),
            Some(crate::CoordinatedStructuralOpJson::RemoveNeuron { .. })
        )
    {
        CHANGE_TYPE_REMOVE_NEURON
    } else {
        CHANGE_TYPE_COORDINATED_STRUCTURAL
    }
}

fn apply_impact_to_coordinated(
    candidate: &mut crate::CoordinatedStructuralCandidateJson,
    impact_scores: &HashMap<String, f32>,
    neuron_type_map: &HashMap<&str, &str>,
    target_squash_map: &HashMap<&str, &str>,
    calibration_correction: &CalibrationCorrection,
) {
    let target_uuid = candidate
        .operations
        .iter()
        .rev()
        .map(|op| match op {
            crate::CoordinatedStructuralOpJson::AddSynapse { to_neuron_uuid, .. } => {
                to_neuron_uuid.as_str()
            }
            crate::CoordinatedStructuralOpJson::RemoveSynapse { to_neuron_uuid, .. } => {
                to_neuron_uuid.as_str()
            }
            crate::CoordinatedStructuralOpJson::SetWeight { to_neuron_uuid, .. } => {
                to_neuron_uuid.as_str()
            }
            crate::CoordinatedStructuralOpJson::ChangeSquash { neuron_uuid, .. } => {
                neuron_uuid.as_str()
            }
            crate::CoordinatedStructuralOpJson::SetBias { neuron_uuid, .. } => neuron_uuid.as_str(),
            crate::CoordinatedStructuralOpJson::AddNeuron { neuron_uuid, .. } => {
                neuron_uuid.as_str()
            }
            crate::CoordinatedStructuralOpJson::RemoveNeuron { neuron_uuid } => {
                neuron_uuid.as_str()
            }
        })
        .next()
        .unwrap_or("");

    let is_hidden = neuron_type_map
        .get(target_uuid)
        .is_none_or(|t| *t != "output");
    let impact = if is_hidden {
        impact_scores
            .get(target_uuid)
            .copied()
            .unwrap_or(0.1)
            .clamp(0.0, 1.0)
    } else {
        1.0
    };

    candidate.expected_creature_score_gain *= impact;

    // Issue #1056: Apply coordinated prediction calibration.
    // Coordinated candidates lack per-sample improved counts, so use flat calibration.
    // Issue #1131: Scaled by the per-creature failure-cache correction.
    // Issue #1162: prefer the per-(change_type, target_squash) specific value
    // when the target neuron's squash is known.
    //
    // Issue #1425: a single-op `RemoveNeuron` coordinated candidate is
    // functionally a `remove-neuron` (harmful-neuron) change and is recorded
    // in the failure cache under that change type. Use the remove-neuron
    // correction key for it so repeated remove-neuron over-predictions (the
    // ~800× over-prediction in failure bucket `247b83ab`) shrink future
    // remove-neuron predictions, rather than the generic coordinated-structural
    // correction which never learns from remove-neuron-keyed failures.
    let change_type = coordinated_candidate_change_type(candidate);
    let target_squash = target_squash_map.get(target_uuid).copied();
    let coordinated_calibration = crate::analysis::constants::COORDINATED_PREDICTION_CALIBRATION
        * calibration_correction.correction_for(change_type, target_squash);
    candidate.expected_creature_score_gain = apply_prediction_calibration(
        candidate.expected_creature_score_gain,
        coordinated_calibration,
    );
}

/// Apply impact discounting, sorting, diversification, and truncation to all candidate sets.
///
/// This is the main post-processing entry point, called after the parallel analysis loop
/// completes and after structural pattern discovery (collapse hidden neurons).
pub(crate) fn apply_post_processing(
    helpful_results: &mut Vec<CandidateSynapseJson>,
    harmful_results: &mut Vec<CandidateSynapseJson>,
    coordinated_structural_results: &mut Vec<crate::CoordinatedStructuralCandidateJson>,
    input: &crate::AnalyzeSynapsesInput,
    cache: &RecordCache,
    order_map: &HashMap<String, usize>,
) -> PostProcessingMetrics {
    // Issue #128: Apply impact-based discounting and set creature-level metrics.
    let impact_scores = compute_impact_scores_for_discounting(&input.creature, cache);
    // Issue #943: Borrow uuid and neuron_type from input instead of cloning.
    let neuron_type_map: HashMap<&str, &str> = input
        .creature
        .neurons
        .iter()
        .map(|n| (n.uuid.as_str(), n.neuron_type.as_str()))
        .collect();

    // Issue #1162: uuid -> target squash map. Used so per-candidate
    // calibration can prefer the (change_type, target_squash) specific
    // correction when the failure-cache supplies enough evidence.
    let target_squash_map: HashMap<&str, &str> = input
        .creature
        .neurons
        .iter()
        .map(|n| (n.uuid.as_str(), n.squash.as_str()))
        .collect();

    // Issue #730: Compute per-neuron and total error for creature-level calibration.
    let error_sq_map = compute_neuron_error_sq_map(input, cache);
    let total_error_sq: f32 = error_sq_map.values().sum();

    // Issue #1131: Derive per-creature calibration correction from the failure cache.
    // This scales the global *_PREDICTION_CALIBRATION constants multiplicatively so
    // creatures whose recent predictions over-estimated actual outcomes receive
    // additional discounting on subsequent candidates.
    let calibration_correction =
        CalibrationCorrection::from_failure_cache(input.failure_cache.as_deref().unwrap_or(&[]));

    // Apply impact discounting to helpful synapse candidates
    for candidate in helpful_results.iter_mut() {
        let target_error_sq = error_sq_map
            .get(candidate.to_neuron_uuid.as_str())
            .copied()
            .unwrap_or(0.0);
        apply_impact_to_helpful(
            candidate,
            &impact_scores,
            &neuron_type_map,
            &target_squash_map,
            order_map,
            target_error_sq,
            total_error_sq,
            &calibration_correction,
        );
    }

    // Apply impact discounting to harmful synapse candidates
    for candidate in harmful_results.iter_mut() {
        apply_impact_to_harmful(
            candidate,
            &impact_scores,
            &neuron_type_map,
            &target_squash_map,
            order_map,
            &calibration_correction,
        );
    }

    // Apply impact discounting to coordinated candidates
    for candidate in coordinated_structural_results.iter_mut() {
        apply_impact_to_coordinated(
            candidate,
            &impact_scores,
            &neuron_type_map,
            &target_squash_map,
            &calibration_correction,
        );
    }

    // Issue #557, #1191: Drop add-synapse candidates whose expected gain is
    // below the absolute noise floor. Predictions in the 1e-7 range are
    // dominated by floating-point round-off in the downstream evaluator (see
    // Issue #1189 failure cache evidence) and waste evaluation budget. The
    // helper records its drops on the global counter
    // (`candidates_below_gain_floor_total`).
    let _helpful_floor_dropped = apply_min_expected_gain_floor_for_synapses(helpful_results);
    let _harmful_floor_dropped = apply_min_expected_gain_floor_for_synapses(harmful_results);
    // Issue #1110, #1128: Synapse-analysis-internal coordinated candidates
    // (e.g. `detect_collapsible_hidden_neurons`, `detect_noisy_vs_trusted`)
    // keep the `> 0.0` filter here because their raw pre-calibration gains
    // can be legitimately small (low-signal unit-test inputs) while still
    // being meaningful candidates worth testing. The 1e-5 production floor
    // is applied by the orchestration (`analyze_all`) final sweep via
    // `apply_coordinated_gain_floor`, after module boost and diversity
    // reranking, which is the FFI-facing path that issue #1127 evidence
    // was captured from.
    coordinated_structural_results.retain(|c| c.expected_creature_score_gain > 0.0);

    // Issue #910: Log distribution of synapse candidates by source type
    log_source_type_distribution(helpful_results, &neuron_type_map);

    // Sort all candidate lists by expected_creature_score_gain (highest first)
    helpful_results.sort_by(|a, b| {
        b.expected_creature_score_gain
            .total_cmp(&a.expected_creature_score_gain)
    });
    harmful_results.sort_by(|a, b| {
        b.expected_creature_score_gain
            .total_cmp(&a.expected_creature_score_gain)
    });
    coordinated_structural_results.sort_by(|a, b| {
        b.expected_creature_score_gain
            .total_cmp(&a.expected_creature_score_gain)
    });

    // Issue #513: Generate weight variants for helpful synapse candidates.
    // Each candidate gets conservative (0.5×), gentle-nudge (0.25×), and micro-nudge (0.1×)
    // weight variants. This maximises the pay-off from the expensive discovery process.
    // Issue #1163: pass the per-variant calibration so the effective
    // expected-improvement multiplier is `min(static, calibrated)`.
    *helpful_results =
        crate::analysis::utils::pair_synapse_candidates_with_weight_variants_calibrated(
            std::mem::take(helpful_results),
            input.max_candidates,
            Some(&calibration_correction),
        );

    // Issue #510: Generate conservative weight variants for coordinated-structural candidates.
    // AddSynapse weights are scaled to 0.2× (conservative), 0.1× (gentle nudge), 0.05× (micro-nudge).
    *coordinated_structural_results =
        crate::analysis::utils::pair_coordinated_structural_with_weight_variants(
            std::mem::take(coordinated_structural_results),
            input.max_candidates,
        );

    // Deadline coverage: diversify within the top-K for exploration diversity
    if input.analysis_deadline_ms.is_some() {
        use crate::analysis::constants::DIVERSIFY_TOP_K;
        shuffle_within_top_k(
            helpful_results.as_mut_slice(),
            input.random_seed,
            "synapse:helpful_candidates:top_k",
            DIVERSIFY_TOP_K,
        );
        shuffle_within_top_k(
            harmful_results.as_mut_slice(),
            input.random_seed,
            "synapse:harmful_candidates:top_k",
            DIVERSIFY_TOP_K,
        );
        shuffle_within_top_k(
            coordinated_structural_results.as_mut_slice(),
            input.random_seed,
            "synapse:coordinated_structural_candidates:top_k",
            DIVERSIFY_TOP_K,
        );
    }

    // Track candidates_found before truncation
    let candidates_found =
        helpful_results.len() + harmful_results.len() + coordinated_structural_results.len();

    if let Some(limit) = input.max_candidates {
        let (h1, h2, c) = truncate_combined_synapse_candidate_sets(
            std::mem::take(helpful_results),
            std::mem::take(harmful_results),
            std::mem::take(coordinated_structural_results),
            limit,
            input.analysis_deadline_ms.is_some(),
        );
        *helpful_results = h1;
        *harmful_results = h2;
        *coordinated_structural_results = c;
    }

    let candidates_returned =
        helpful_results.len() + harmful_results.len() + coordinated_structural_results.len();

    PostProcessingMetrics {
        candidates_found,
        candidates_returned,
        calibration_corrections: calibration_correction.as_map().clone(),
    }
}

/// Metrics returned from post-processing for inclusion in analysis metadata.
pub(crate) struct PostProcessingMetrics {
    pub candidates_found: usize,
    pub candidates_returned: usize,
    /// Issue #1131: Per-change-type calibration corrections derived from the
    /// failure cache and applied multiplicatively to the global prediction
    /// calibration constants. Exposed via analysis metadata for observability.
    pub calibration_corrections: HashMap<String, f32>,
}

/// Parameters for building analysis metadata.
pub(crate) struct MetadataParams<'a> {
    pub target_value_seen: bool,
    pub saturation_aware_used: bool,
    pub candidates_found: usize,
    pub candidates_returned: usize,
    pub analysis_timed_out: bool,
    pub completed_focus_neurons: usize,
    pub total_focus_neurons: usize,
    pub saw_any_input: bool,
    pub input_min: usize,
    pub input_max: usize,
    pub error_values: &'a [f32],
    pub timing_collector: &'a crate::analysis::shared::TimingCollector,
    /// Issue #1021: MCMC diagnostics summary.
    pub mcmc_summary:
        Option<crate::analysis::diagnostics::mcmc_diagnostics::McmcDiagnosticsSummary>,
    /// Issue #1131: Per-change-type calibration corrections from the failure cache.
    pub calibration_corrections: HashMap<String, f32>,
    /// Issue #1143: count of new add-synapse sources dropped because their
    /// target neuron was already saturated.
    pub target_saturated_drops: u32,
    /// Issue #1270: count of 1-in/1-out hidden-neuron collapse candidates
    /// rejected by the bypass-weight floor in
    /// `detect_collapsible_hidden_neurons`.
    pub collapse_bypass_below_floor_drops: u32,
    /// Issue #1544: count of helpful add-synapse candidates dropped by the CPU
    /// pre-reject screen before GPU submit.
    pub cpu_pre_reject_no_signal_drops: u32,
}

/// Build the analysis metadata from collected atomic flags and timing data.
pub(crate) fn build_metadata(
    params: &MetadataParams<'_>,
) -> crate::analysis::shared::SynapseAnalysisMetadata {
    use crate::analysis::gpu::GpuAnalyzer;

    let error_distribution =
        crate::analysis::scoring::error_distribution::ErrorDistribution::from_errors(
            params.error_values,
        );

    crate::analysis::shared::SynapseAnalysisMetadata {
        target_value_available: params.target_value_seen,
        saturation_aware_simulation_used: params.saturation_aware_used,
        candidates_found: params.candidates_found,
        candidates_returned: params.candidates_returned,
        timed_out: params.analysis_timed_out,
        completed_focus_neurons: params.completed_focus_neurons,
        total_focus_neurons: params.total_focus_neurons,
        input_index_min_seen_with_records: if params.saw_any_input {
            Some(params.input_min)
        } else {
            None
        },
        input_index_max_seen_with_records: if params.saw_any_input {
            Some(params.input_max)
        } else {
            None
        },
        timing: params.timing_collector.finalize(),
        gpu_info: GpuAnalyzer::get_adapter_info(),
        error_distribution,
        discovery_module_stats: Vec::new(),
        mcmc_diagnostics: params.mcmc_summary.clone(),
        // Issue #1129: populated by orchestration after metadata is built.
        //
        // Issue #1143: seed the breakdown with the target-saturated drop
        // count here so it survives `aggregate_synapse_rejection_breakdown`,
        // which only appends per-target `no_candidate_reasons`.
        rejection_breakdown: {
            let mut b = crate::analysis::diagnostics::RejectionBreakdown::new();
            b.record_many_u32(
                crate::analysis::diagnostics::rejection_reasons::REJECTION_TARGET_SATURATED,
                params.target_saturated_drops,
            );
            // Issue #1270: record bypass-weight-floor drops from the
            // hidden-neuron collapse detector so the dispatch-side counter
            // shows up in the drought diagnostic.
            b.record_many_u32(
                crate::analysis::diagnostics::rejection_reasons::REJECTION_COORDINATED_COLLAPSE_BYPASS_WEIGHT_BELOW_FLOOR,
                params.collapse_bypass_below_floor_drops,
            );
            // Issue #1544: record CPU pre-reject drops so the drought diagnostic
            // can distinguish a cheap CPU screen-out from a genuine drought.
            b.record_many_u32(
                crate::analysis::diagnostics::rejection_reasons::REJECTION_CPU_PRE_REJECT_NO_SIGNAL,
                params.cpu_pre_reject_no_signal_drops,
            );
            b
        },
        top_level_summary: None,
        // Issue #1131: per-creature calibration corrections derived from failure cache.
        calibration_corrections: params.calibration_corrections.clone(),
        // Issue #1132: populated by orchestration once the outcome log is decided.
        discovery_mode: crate::analysis::discovery_mode::DiscoveryMode::Normal,
        rolling_success_rate: 1.0,
        // Issue #1202: populated by orchestration when in drought.
        drought_diagnostic: None,
        // Issue #1424: populated by orchestration on the alarm crossing.
        creature_drought_alarm: None,
        // Issue #1444: populated by orchestration's fail-fast gate only.
        insufficient_recording: None,
        // Issue #1931: a pass that reached result assembly ran its GPU work.
        gpu_wedged: false,
        // Issue #1791: set by `analyse_synapses` from the real
        // `apply_target_cooldown` return value.
        target_cooldown_skipped: 0,
        // Issue #1791: set by `finalise_synapse_results` from the per-target
        // diagnostics.
        target_pass_outcomes: Vec::new(),
        // Issue #1802: set by the orchestrator once the breakdown is final.
        candidate_reconciliation: None,
    }
}

// =============================================================================
// Tests (Issue #1425) — remove-neuron / harmful-neuron calibration correction
// =============================================================================

#[cfg(test)]
mod remove_neuron_calibration_tests {
    //! Issue #1425: harmful-neuron (`remove-neuron`) candidates must have the
    //! failure-cache calibration correction applied to their predicted gain.
    //! A single-op `RemoveNeuron` coordinated candidate is keyed under
    //! `remove-neuron`, so repeated remove-neuron over-predictions shrink future
    //! remove-neuron predictions instead of being re-emitted every pass.

    use super::{apply_impact_to_coordinated, coordinated_candidate_change_type};
    use crate::analysis::scoring::calibration_correction::{
        CHANGE_TYPE_COORDINATED_STRUCTURAL, CHANGE_TYPE_REMOVE_NEURON, CalibrationCorrection,
        FailureCacheEntry,
    };
    use crate::{CoordinatedStructuralCandidateJson, CoordinatedStructuralOpJson};
    use std::collections::HashMap;

    /// Build a failure-cache entry mirroring the `247b83ab` evidence shape:
    /// `change_type = remove-neuron`, predicted ≈ 0.166, actual ≈ 0 (slightly
    /// negative) — a ~800× over-prediction.
    fn remove_neuron_failure() -> FailureCacheEntry {
        FailureCacheEntry {
            change_type: CHANGE_TYPE_REMOVE_NEURON.to_string(),
            expected_error_reduction: 0.165_710_48,
            actual_error_reduction: -0.000_207_19,
            target_squash: None,
            variant_key: None,
            target_uuid: None,
            improved_count: None,
            total_count: None,
            age_epochs: None,
        }
    }

    fn single_remove_neuron_candidate(gain: f32) -> CoordinatedStructuralCandidateJson {
        CoordinatedStructuralCandidateJson {
            remove_neuron_compensation: None,
            constant_neuron_bias_fold: None,
            operations: vec![CoordinatedStructuralOpJson::RemoveNeuron {
                neuron_uuid: "h-1075292892".to_string(),
            }],
            expected_creature_score_gain: gain,
            comment: None,
        }
    }

    /// Apply `apply_impact_to_coordinated` with a fixed impact of 1.0 for the
    /// target so the calibration factor is the only variable under test.
    fn calibrated_gain(
        candidate: &mut CoordinatedStructuralCandidateJson,
        correction: &CalibrationCorrection,
    ) -> f32 {
        let mut impact_scores: HashMap<String, f32> = HashMap::new();
        impact_scores.insert("h-1075292892".to_string(), 1.0);
        let neuron_type_map: HashMap<&str, &str> = HashMap::new();
        let target_squash_map: HashMap<&str, &str> = HashMap::new();
        apply_impact_to_coordinated(
            candidate,
            &impact_scores,
            &neuron_type_map,
            &target_squash_map,
            correction,
        );
        candidate.expected_creature_score_gain
    }

    /// Criterion 3: a single-op `RemoveNeuron` coordinated candidate is keyed
    /// under the `remove-neuron` change type; everything else stays
    /// `coordinated-structural`.
    #[test]
    fn single_remove_neuron_is_keyed_as_remove_neuron() {
        let remove = single_remove_neuron_candidate(0.1);
        assert_eq!(
            coordinated_candidate_change_type(&remove),
            CHANGE_TYPE_REMOVE_NEURON
        );

        // Multi-op group containing a RemoveNeuron stays coordinated-structural.
        let multi = CoordinatedStructuralCandidateJson {
            remove_neuron_compensation: None,
            constant_neuron_bias_fold: None,
            operations: vec![
                CoordinatedStructuralOpJson::SetBias {
                    neuron_uuid: "out-0".to_string(),
                    bias: 0.1,
                },
                CoordinatedStructuralOpJson::RemoveNeuron {
                    neuron_uuid: "h-1".to_string(),
                },
            ],
            expected_creature_score_gain: 0.1,
            comment: None,
        };
        assert_eq!(
            coordinated_candidate_change_type(&multi),
            CHANGE_TYPE_COORDINATED_STRUCTURAL
        );

        // A non-removal single op stays coordinated-structural too.
        let add = CoordinatedStructuralCandidateJson {
            remove_neuron_compensation: None,
            constant_neuron_bias_fold: None,
            operations: vec![CoordinatedStructuralOpJson::AddSynapse {
                from_neuron_uuid: "a".to_string(),
                to_neuron_uuid: "b".to_string(),
                weight: 0.5,
            }],
            expected_creature_score_gain: 0.1,
            comment: None,
        };
        assert_eq!(
            coordinated_candidate_change_type(&add),
            CHANGE_TYPE_COORDINATED_STRUCTURAL
        );
    }

    /// Criteria 1 & 2: replaying the cached remove-neuron failures shrinks the
    /// predicted gain of a fresh remove-neuron candidate toward the observed
    /// ≈ 0 — far below the gain it receives under a neutral (empty) cache.
    #[test]
    fn remove_neuron_failures_shrink_predicted_gain() {
        // Nine cached remove-neuron failures, matching the evidence bucket.
        let cache: Vec<FailureCacheEntry> = (0..9).map(|_| remove_neuron_failure()).collect();
        let correction = CalibrationCorrection::from_failure_cache(&cache);

        // The remove-neuron correction must learn the ~800× over-prediction and
        // collapse to (near) the floor.
        let learned = correction.correction_for(CHANGE_TYPE_REMOVE_NEURON, None);
        assert!(
            learned <= 0.01,
            "remove-neuron correction should be near the floor, got {learned}"
        );

        let raw_gain = 0.165_710_48_f32;
        let mut with_failures = single_remove_neuron_candidate(raw_gain);
        let gain_with = calibrated_gain(&mut with_failures, &correction);

        let neutral = CalibrationCorrection::neutral();
        let mut without = single_remove_neuron_candidate(raw_gain);
        let gain_without = calibrated_gain(&mut without, &neutral);

        // Both must remain positive (sign preserved) but the learned correction
        // must shrink the prediction by roughly the over-prediction factor.
        assert!(gain_with > 0.0 && gain_without > 0.0);
        assert!(
            gain_with < gain_without * 0.05,
            "learned correction must shrink the gain by >20×: with={gain_with}, without={gain_without}"
        );
    }

    /// Regression guard: the remove-neuron correction must NOT bleed into a
    /// coordinated-structural candidate — only remove-neuron-keyed candidates
    /// are discounted by remove-neuron failures.
    #[test]
    fn coordinated_structural_unaffected_by_remove_neuron_failures() {
        let cache: Vec<FailureCacheEntry> = (0..9).map(|_| remove_neuron_failure()).collect();
        let correction = CalibrationCorrection::from_failure_cache(&cache);

        let raw_gain = 0.165_710_48_f32;
        let mut coordinated = CoordinatedStructuralCandidateJson {
            remove_neuron_compensation: None,
            constant_neuron_bias_fold: None,
            operations: vec![
                CoordinatedStructuralOpJson::RemoveSynapse {
                    from_neuron_uuid: "a".to_string(),
                    to_neuron_uuid: "h-1075292892".to_string(),
                },
                CoordinatedStructuralOpJson::RemoveNeuron {
                    neuron_uuid: "h-1075292892".to_string(),
                },
            ],
            expected_creature_score_gain: raw_gain,
            comment: None,
        };
        let gain_coord = calibrated_gain(&mut coordinated, &correction);

        let neutral = CalibrationCorrection::neutral();
        let mut coordinated_neutral = coordinated.clone();
        coordinated_neutral.expected_creature_score_gain = raw_gain;
        let gain_neutral = calibrated_gain(&mut coordinated_neutral, &neutral);

        // No coordinated-structural failures recorded, so the correction is
        // neutral for this candidate — gain is identical with or without the
        // remove-neuron failures.
        assert!(
            (gain_coord - gain_neutral).abs() < f32::EPSILON,
            "coordinated-structural gain must be unaffected: {gain_coord} vs {gain_neutral}"
        );
    }
}
