//! FFI boundary integration tests.

#[path = "../common/mod.rs"]
mod common;

mod issue_1027_memory_usage_ffi;
mod issue_1028_memory_budget;
mod issue_1184_recurrent_synapse_rejection;
mod issue_1188_strip_pattern_rejection;
mod issue_1314_task_descriptor_plumbing;
mod issue_1402_lowercase_task_descriptor_regression;
mod issue_1407_focus_shared_deadline;
mod issue_1445_focus_selection_diversity;
mod issue_1530_dispatch_honest_remove_neuron_gain;
mod issue_1766_structural_focus_selection;
mod issue_1767_structural_removal_triage;
mod issue_1779_bias_fold_wire_contract;
mod issue_1866_cleanup_dir_path_guard;
mod issue_1867_creature_input_bounds;
mod issue_1923_activation_weighted_removal_gate;
mod issue_1932_gpu_wedged_classification;
mod issue_2020_observation_width;
mod issue_2045_input_guard_helper;
mod issue_574_ffi_json_fuzz_edge_cases;
mod issue_711_ffi_safety_unsafe_markers;
mod issue_950_numeric_neuron_ids;
mod issue_952_uuid_only_ffi_contract;
mod issue_975_ffi_boundary_error_handling;
